modLoader="javafml"
loaderVersion="[43,)"
license="GPL-3.0"

[[mods]]
modId="nanny"
version="1.0.1"
displayName="NaNny"
displayURL="https://github.com/Vonr/NaNny"
authors="Qther"
description='''
Because some mods can't keep their floats in control.
'''

[[dependencies.nanny]]
    modId="forge"
    mandatory=true
    versionRange="[48,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.nanny]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2, 1.20.3)"
    ordering="NONE"
    side="SERVER"
